export const MAIN_ROUTE = '/'
export const PORTFOLIO_ROUTE = '/portfolio'
export const WORK_ROUTE = '/work'
export const AUTH_ROUTE = '/auth'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'